package com.SchoolManagementSystem.system.exception.model;

public enum ErrorCode {

    // Generic
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    SERVER_PROBLEM,
    ENDPOINT_NOT_FOUND,
    INVALID_URL,


    // Authentication
    EMAIL_ALREADY_EXISTS,
    NATIONAL_ID_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    UNAUTHENTICATED,
    UNAUTHORIZED,
    FORBIDDEN,
    ACCESS_DENIED,
    INVALID_TOKEN,
    ACCOUNT_NOT_ACTIVATED_YET,


    // User
    USER_NOT_FOUND,
    USER_ALREADY_ACTIVATED,
    USER_ALREADY_DEACTIVATED,
    UNSUPPORTED_ROLE,


    // School
    SCHOOL_NOT_FOUND,
    SCHOOL_ALREADY_EXISTS,


    // Principal
    PRINCIPAL_NOT_FOUND,


    // Teacher
    TEACHER_NOT_FOUND,
    TEACHER_ALREADY_ASSIGNED_AT_THIS_TIME,
    TEACHER_DOES_NOT_TEACH_SUBJECT,


    // Secretary
    SECRETARY_NOT_FOUND,


    // Librarian
    LIBRARIAN_NOT_FOUND,


    // Student
    STUDENT_NOT_FOUND,
    REGISTRATION_NUMBER_ALREADY_EXISTS,


    // Guardian
    GUARDIAN_NOT_FOUND,
    PRIMARY_GUARDIAN_ALREADY_EXISTS,
    GUARDIAN_ALREADY_CONNECTED,


    // Subject
    SUBJECT_NOT_FOUND,
    SUBJECT_ALREADY_EXISTS,


    // Class
    CLASS_NOT_FOUND,
    CLASS_ALREADY_EXISTS,
    CLASS_ALREADY_HAVE_EXTRA_PERIOD,
    MAX_PERIODS_REACHED,


    // Schedule
    CLASS_SCHEDULE_NOT_FOUND,
    SCHOOL_CLASS_NOT_FOUND,
    CANT_ADD_PERIOD_IN_HOLIDAY,
    CLASS_ALREADY_HAS_TEACHER_ASSIGNED_AT_THIS_TIME,


    // Semester
    SEMESTER_NOT_FOUND,
    SEMESTER_ALREADY_EXISTS,


    // Attendance
    ATTENDANCE_NOT_FOUND,
    ATTENDANCE_ALREADY_EXISTS,
    INVALID_ATTENDANCE_DAY,


    // Education
    EDUCATION_RECORD_NOT_FOUND,


    // Assessment
    ASSESSMENT_NOT_FOUND,
    ASSESSMENT_RESULT_NOT_FOUND,


    // Teacher Subject
    TEACHER_SUBJECT_NOT_FOUND,


    // Library
    LIBRARY_NOT_FOUND,
    LIBRARY_BOOK_NOT_FOUND,
    BORROW_NOT_FOUND,


    // Finance
    PAYMENT_NOT_FOUND,
    DISCOUNT_NOT_FOUND,
    CLASS_FEE_NOT_FOUND,
    STUDENT_DISCOUNT_NOT_FOUND,
    FEE_TYPE_NOT_FOUND,


    // Communication
    ANNOUNCEMENT_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,


    // File
    FILE_NOT_FOUND,
    FILE_UPLOAD_FAILED,
    FILE_DELETE_FAILED,
    FILE_LOAD_FAILED,
    FILE_STORAGE_FAILED,
    FILE_EMPTY,
    INVALID_IMAGE_TYPE,
    INVALID_DOCUMENT_TYPE,
    IMAGE_SIZE_EXCEEDED,
    DOCUMENT_SIZE_EXCEEDED,
    INVALID_OWNER_TYPE,


    // Relation
    RELATION_NOT_FOUND,
    RELATION_ALREADY_EXISTS,
    CANT_DELETE_PRIMARY_GUARDIAN,


    // Special
    OWNER_NOT_FOUND,
    NO_GUARDIANS_WITHOUT_STUDENTS,
    NO_STUDENTS_WITHOUT_GUARDIAN,
    INVALID_PASSWORD,
    USE_TENANT_LOGIN,
    NO_TENANT_SELECTED,
    SCHOOL_NAME_ALREADY_EXIST,
    CANT_NAME_BE_EMPTY,
    TEACHER_NOT_ASSIGNED_TO_CLASS,
    YOU_DONT_TEACH_THIS_CLASS,
    EXAM_ALREADY_EXISTS,
    EXAM_NOT_FOUND,
    SUBJECT_NOT_BELONG_TO_CLASS,
    EXAM_TIME_CONFLICT,
    GUARDIAN_HAS_NO_STUDENTS,
    STUDENTS_REQUIRED,
    STUDENT_ALREADY_HAVE_MARK,
    SCORE_OUT_OF_RANGE,
    SCORE_CANT_BE_NULL,
    DUPLICATE_STUDENT,
    STUDENT_NOT_IN_CLASS,
    STUDENT_HAS_NO_CLASS, GRADE_LEVEL_NOT_AVAILABLE, SCHOOL_REQUEST_NOT_FOUND, SCHOOL_REQUEST_ALREADY_REVIEWED, INVALID_ANNOUNCEMENT_TARGET, CANT_ONE_TWICE, CANT_EDIT_ONE_TWICE, FEE_STRUCTURE_ALREADY_EXISTS, FEE_STRUCTURE_NOT_FOUND, INVALID_FEE_STRUCTURE, INVALID_FEE_AMOUNT, ACADEMIC_YEAR_NOT_FOUNT, ACADEMIC_YEAR_NOT_FOUND, INVALID_SEMESTER_DATES, SEMESTERS_OVERLAP, INVALID_SEMESTER, INVALID_PAYMENT_METHOD, INVALID_PAYMENT_AMOUNT, FEE_PAYMENT_NOT_FOUND, FEE_NOT_FOUND, RECEIPT_NUMBER_ALREADY_EXISTS, PAYMENT_EXCEEDS_REMAINING, DISCOUNT_ALREADY_EXISTS, INVALID_DISCOUNT, DONATION_NOT_FOUND, DONATION_CAMPAIGN_NOT_FOUND, DONATION_CAMPAIGN_NOT_ACTIVE, INVALID_DONATION_AMOUNT, INVALID_DONATION_CAMPAIGN, INVALID_DONATION_TARGET, INVALID_DONATION_DATE, FEE_ALREADY_PAID, EXAM_RESULT_NOT_FOUND
}