spring.config.import=optional:file:.env[.properties]

spring.application.name=school-service
eureka.client.service-url.defaultZone=${EUREKA_URL}

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

server.port=8081

jwt.secret=${JWT_SECRET}
gateway.secret=${GATEWAY_SECRET}


storage.location=${STORAGE_LOCATION:uploads}

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.messages.basename=messages
spring.messages.encoding=UTF-8

storage.image-types=image/jpeg,image/png,image/webp
storage.document-types=application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document
storage.max-image-size=5242880
storage.max-document-size=20971520