package com.SchoolManagementSystem.System.exception.model;

public enum ErrorCode {

    // Student
    STUDENT_NOT_FOUND,
    REGISTRATION_NUMBER_ALREADY_EXISTS,

    // Guardian
    GUARDIAN_NOT_FOUND,
    PRIMARY_GUARDIAN_ALREADY_EXISTS,
    GUARDIAN_ALREADY_CONNECTED,

    // Teacher
    TEACHER_NOT_FOUND,

    // Secretary
    SECRETARY_NOT_FOUND,

    // Principal
    PRINCIPAL_NOT_FOUND,

    // Librarian
    LIBRARIAN_NOT_FOUND,

    // Subject
    SUBJECT_NOT_FOUND,
    SUBJECT_ALREADY_EXISTS,

    // School Class
    CLASS_NOT_FOUND,
    MAX_PERIODS_REACHED,

    // Attendance
    ATTENDANCE_NOT_FOUND,
    ATTENDANCE_ALREADY_EXISTS,
    INVALID_ATTENDANCE_DAY,

    // SemesterName
    SEMESTER_NOT_FOUND,

    // Education
    EDUCATION_RECORD_NOT_FOUND,

    // Assessment
    ASSESSMENT_NOT_FOUND,
    ASSESSMENT_RESULT_NOT_FOUND,

    // Library
    LIBRARY_NOT_FOUND,
    LIBRARY_BOOK_NOT_FOUND,
    BORROW_NOT_FOUND,

    // School
    SCHOOL_NOT_FOUND,

    // Finance
    PAYMENT_NOT_FOUND,
    DISCOUNT_NOT_FOUND,
    CLASS_FEE_NOT_FOUND,
    STUDENT_DISCOUNT_NOT_FOUND,
    FEE_TYPE_NOT_FOUND,

    // Communication
    ANNOUNCEMENT_NOT_FOUND,
    NOTIFICATION_NOT_FOUND,

    // Authentication
    EMAIL_ALREADY_EXISTS,
    NATIONAL_ID_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    UNAUTHENTICATED,
    FORBIDDEN,

    // File
    FILE_NOT_FOUND,
    FILE_UPLOAD_FAILED,
    FILE_DELETE_FAILED,

    // Generic
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    USER_ALREADY_ACTIVATED, USER_ALREADY_DEACTIVATED, USER_NOT_FOUND, UNSUPPORTED_ROLE,

    SCHOOL_CLASS_NOT_FOUND,

    TEACHER_SUBJECT_NOT_FOUND,
    CLASS_ALREADY_HAVE_EXTRA_PERIOD,
    CLASS_SCHEDULE_NOT_FOUND,
    CANT_ADD_PERIOD_IN_HOLIDAY,
    SEMESTER_ALREADY_EXISTS,
    CLASS_ALREADY_EXISTS,
    TEACHER_DOES_NOT_TEACH_SUBJECT,
    OWNER_NOT_FOUND,
    TEACHER_ALREADY_ASSIGNED_AT_THIS_TIME,
    CLASS_ALREADY_HAS_TEACHER_ASSIGNED_AT_THIS_TIME,
    UNAUTHORIZED,
    SERVER_PROBLEM,
    FILE_LOAD_FAILED,
    FILE_STORAGE_FAILED,
    FILE_EMPTY,
    INVALID_IMAGE_TYPE,
    IMAGE_SIZE_EXCEEDED,
    DOCUMENT_SIZE_EXCEEDED,
    INVALID_DOCUMENT_TYPE,
    INVALID_OWNER_TYPE,
    RELATION_NOT_FOUND,
    RELATION_ALREADY_EXISTS,
    NO_GUARDIANS_WITHOUT_STUDENTS,
    NO_STUDENTS_WITHOUT_GUARDIAN,
    CANT_DELETE_PRIMARY_GUARDIAN,
    INVALID_TOKEN,
    ACCESS_DENIED,
    STUDENT_ALREADY_HAVE_MARK,
    DUPLICATE_STUDENT,
    SCORE_CANT_BE_NULL,
    SCORE_CANT_BE_NEGATIVE,
    SCORE_CANT_BE_EXCEEDS_THAN_SCORE,
    SCORE_EXCEEDS_MAX_SCORE,
    SCORE_OUT_OF_RANGE,
    STUDENTS_REQUIRED,
    STUDENT_NOT_IN_CLASS,
    TEACHER_NOT_ASSIGNED_TO_CLASS, EXAM_ALREADY_EXISTS, EXAM_NOT_FOUND, SUBJECT_NOT_BELONG_TO_CLASS, EXAM_TIME_CONFLICT, EXAM_RESULT_NOT_FOUND, GUARDIAN_HAS_NO_STUDENTS, YOU_DONT_TEACH_THIS_CLASS, INVALID_PASSWORD, NO_TENANT_SELECTED, USE_TENANT_LOGIN,  SCHOOL_NAME_ALREADY_EXIST, CANT_NAME_BE_EMPTY, ACCOUNT_NOT_ACTIVATED, ACCOUNT_NOT_ACTIVATED_YET,
}
